#!/usr/bin/env python3
"""
Generates the app icon and the home-screen mark from one source of truth.

The mark is a king and a queen standing side by side -- the two pieces whose
silhouettes are least confusable at launcher size, and the pair that says
"chess" without saying "chess computer".

    python3 tools/generate_app_icon.py

Produces:
    res/drawable/ic_launcher_foreground.xml   adaptive icon, foreground layer
    res/drawable/ic_launcher_monochrome.xml   themed icon (Android 13+), one colour
    res/drawable/logo_mark.xml                same artwork, cropped, for in-app use

The launcher layers are drawn on the 108x108 grid Android expects. Placement is
not eyeballed: the composition is fitted so that its corners sit on the 72dp
circle around the centre, which is the region every launcher mask reveals. The
66dp circle in the documentation is the stricter "key content" guidance -- the
outer ends of the two base bars fall marginally outside it, which is why the
bases, and nothing else, are the parts a round mask may shave.

The two pieces are drawn with a deliberate gap between them. Overlapping them
looks richer in colour, but the themed icon flattens both to a single colour and
overlapping silhouettes fuse there into one unreadable blob.

Both outlines are original work: hand-placed coordinates, not traced from
another set. The board pieces in res/drawable/piece_*.xml are a different set
(Cburnett, BSD 3-Clause) and are not used here.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "android-app/app/src/main/res/drawable"

WHITE = "#FFFFFF"
BLUE = "#3193C6"

# --------------------------------------------------------------- silhouettes
# Drawn in a 0..100 box, y downwards, standing on y=100.

KING = ("M45,2 L55,2 L55,10 L66,10 L66,20 L55,20 L55,26 "
        "C64,29 71,36 71,44 C71,51 66,57 59,60 "
        "L60,62 L70,62 L70,70 L62,70 C63,80 68,88 76,92 "
        "L86,92 L86,99 L14,99 L14,92 L24,92 "
        "C32,88 37,80 38,70 L30,70 L30,62 L40,62 L41,60 "
        "C34,57 29,51 29,44 C29,36 36,29 45,26 "
        "L45,20 L34,20 L34,10 L45,10 Z")
KING_INK = (14, 86, 2, 99)

QUEEN = ("M50,10 L56,44 L68,18 L70,46 L84,30 L80,52 L20,52 L16,30 L30,46 L32,18 L44,44 Z "
         "M22,56 L78,56 L78,64 L70,64 C71,76 74,86 80,92 L20,92 "
         "C26,86 29,76 30,64 L22,64 Z "
         "M10,94 L90,94 L90,99 L10,99 Z")
QUEEN_BALLS = ((50, 6, 6), (33, 13, 5.5), (67, 13, 5.5), (15, 27, 5.5), (85, 27, 5.5))
QUEEN_INK = (10, 90, 0, 99)

# Placement: (scale, centre x, baseline y) on the 108 grid.
PLACE_QUEEN = (0.35, 36.8, 72.0)
PLACE_KING = (0.42, 70.1, 72.0)

# Breathing room around the cropped in-app mark, in the same units.
MARGIN = 1.5


def num(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def transform(path, scale, dx, dy):
    """Bake a scale+translate into absolute M/L/C coordinates."""
    out, i = [], 0
    tokens = re.findall(r"[MLCZz]|-?\d*\.?\d+", path)
    axis = 0
    for t in tokens:
        if t in "MLCZz":
            out.append(t.upper())
            axis = 0
        else:
            v = float(t) * scale + (dx if axis % 2 == 0 else dy)
            out.append(num(v))
            axis += 1
    # re-join: command letters followed by their numbers
    s, res = "", []
    for t in out:
        if t in "MLCZ":
            res.append(t)
        else:
            res.append(t)
    text = ""
    for t in res:
        if t in "MLCZ":
            text += ("" if not text else " ") + t
        else:
            text += ("," if text and text[-1] not in "MLCZ " else "") + t
    return text


def ball(cx, cy, r):
    """A circle as pathData -- VectorDrawable has no <circle>."""
    return (f"M{num(cx - r)},{num(cy)} A{num(r)},{num(r)} 0 1,0 {num(cx + r)},{num(cy)} "
            f"A{num(r)},{num(r)} 0 1,0 {num(cx - r)},{num(cy)} Z")


def piece_paths(which, place, dx=0.0, dy=0.0):
    scale, cx, base = place
    tx, ty = cx - 50 * scale + dx, base - 100 * scale + dy
    if which == "king":
        return [transform(KING, scale, tx, ty)]
    parts = [transform(QUEEN, scale, tx, ty)]
    parts += [ball(tx + bx * scale, ty + by * scale, br * scale) for bx, by, br in QUEEN_BALLS]
    return parts


def ink_box(dx=0.0, dy=0.0):
    xs, ys = [], []
    for which, place, ink in (("queen", PLACE_QUEEN, QUEEN_INK), ("king", PLACE_KING, KING_INK)):
        scale, cx, base = place
        tx, ty = cx - 50 * scale + dx, base - 100 * scale + dy
        xs += [tx + ink[0] * scale, tx + ink[1] * scale]
        ys += [ty + ink[2] * scale, ty + ink[3] * scale]
    return min(xs), max(xs), min(ys), max(ys)


HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  {what}

  Generated by tools/generate_app_icon.py - do not edit by hand.
  King and queen, original outlines. Not the Cburnett board set.
-->
"""


def vector(what, w, h, vw, vh, paths):
    body = "".join(
        f'    <path\n        android:pathData="{d}"\n        android:fillColor="{c}" />\n'
        for d, c in paths)
    return (HEADER.format(what=what) +
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{w}dp"\n    android:height="{h}dp"\n'
            f'    android:viewportWidth="{vw}"\n    android:viewportHeight="{vh}">\n'
            f"{body}</vector>\n")


def write(name, text):
    (RES / name).write_text(text)
    print(f"  {name}  ({len(text)} bytes)")


def main():
    queen = piece_paths("queen", PLACE_QUEEN)
    king = piece_paths("king", PLACE_KING)

    write("ic_launcher_foreground.xml", vector(
        "Adaptive launcher icon, foreground layer.", 108, 108, 108, 108,
        [(d, BLUE) for d in queen] + [(d, WHITE) for d in king]))

    write("ic_launcher_monochrome.xml", vector(
        "Themed icon (Android 13+). One colour; the system tints it.",
        108, 108, 108, 108,
        [(d, WHITE) for d in queen + king]))

    # In-app mark: same artwork with the launcher's masking margin removed.
    # A small margin stays -- without it the king's base bar ends exactly on the
    # viewport edge, which reads as a crop rather than as a deliberate fit.
    m = MARGIN
    x0, x1, y0, y1 = ink_box()
    qp = piece_paths("queen", PLACE_QUEEN, m - x0, m - y0)
    kp = piece_paths("king", PLACE_KING, m - x0, m - y0)
    w, h = x1 - x0 + 2 * m, y1 - y0 + 2 * m
    write("logo_mark.xml", vector(
        "The mark on its own, cropped to the artwork. Used on the home screen.",
        round(w), round(h), num(w), num(h),
        [(d, BLUE) for d in qp] + [(d, WHITE) for d in kp]))


if __name__ == "__main__":
    main()
